"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalStyle } from "./style/globals";
import { ThemeProvider } from "styled-components";
import { DarkTheme } from "./style/theme";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ThemeProvider theme={DarkTheme}>
      <GlobalStyle></GlobalStyle>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ThemeProvider>
  );
}
