import "./globals.css";
import { Metadata } from "next";
import { StateContext, StateProvider } from "./hooks/useStateManagement";


// import { CategoryProvider } from "./hooks/useCategories";
import logging from "./utils/logger";
// import { setting, categories } from "./layout";


import { Setting } from "./server/setting/settings";
import { CategoryManager  } from "./server/setting/categoryManager";
import sqlite3 from 'sqlite3'
import { open } from 'sqlite'
import { FavouriteQueries } from "./server/setting/favouriteQueries";
import { AxiosProvider } from "./hooks/useAxios";
import { QueryStateProvider } from "./hooks/useQueryState";

logging.debug("Server started")

const SCHEMA =  `
    create table if not exists setting (
        version text primary key, 
        theme text,
        watchedItems text,
        shippingLocation text,
        shippingPostcode integer,
        itemLocation text,
        marketPlaceId text,
        defaultRefreshIntervalSecond integer
    );

    create table if not exists categories (
        version text primary key,
        categories text
    );

    create table if not exists favouriteQueries (
        id integer primary key autoincrement,
        ebaySearch text
    );
`

const db = await open({
    filename: process.env.DATABASE!,
    // filename: ":memory:",
    driver: sqlite3.Database
})

await db.exec(SCHEMA)

export const setting = await Setting.init(db)
export const categories = await CategoryManager.init(setting, db)
export const favouriteQueries= await FavouriteQueries.init(db)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const serverData = {
      setting: setting.setting,
      categories: categories.categories
  }

  return (
    <>
      <html>
        <body
          className="
            bg-gray-900
            text-gray-400
          "
        >
          <AxiosProvider>
            <StateProvider serverData={serverData}>
              <QueryStateProvider>
                  {children}
              </QueryStateProvider>
            </StateProvider>
          </AxiosProvider>
        </body>
      </html>
    </>
  );
}
